### ISSUE TITLE
Nested Futures

### ISSUE THREAD

**Issue by jon-chuang** [oxalica/async-ffi#13]
Could you provide some details on whether nested futures are possible with async-ffi?

For instance, consider this example:
```rust
// Compile with `crate-type = ["cdylib"]`.
use async_ffi::{FfiFuture, FutureExt};

#[no_mangle]
pub extern "C" fn work(arg: u32) -> FfiFuture<u32> {
    async move {
        let ret = do_some_io(arg).await;
        do_some_sleep(42).await;
        ret
    }
    .into_ffi()
}
```

In that case, don't `do_some_io` and `do_some_sleep` also need to return `FfiFuture` since their return values will be consumed by the importing code's runtime which would expect a certain ABI from them?

Wouldn't this severely limit the plug-and-play-ability of this library? 

Maybe to clarify this, one should analyze the above example and see what the code path is through an executor?

**Comment by jon-chuang** [comment]
Maybe the solution is:
```rust
use async_ffi::{FfiFuture, FutureExt};

#[no_mangle]
pub extern "C" fn work(arg: u32) -> FfiFuture<u32> {
    async move {
        let ret = do_some_io(arg).into_ffi().await;
        do_some_sleep(42).into_ffi().await;
        ret
    }
    .into_ffi()
}
```

A proc macro a la https://github.com/oxalica/async-ffi/issues/12 which handles all of this boilerplate would indeed be even more useful.

**Comment by oxalica** [comment]
> In that case, don't `do_some_io` and `do_some_sleep` also need to return `FfiFuture` since their return values will be consumed by the importing code's runtime which would expect a certain ABI from them?

No. The `FfiFuture` wrapper is only required once in the body of an `extern "C"` function. Because you cannot (and is undefined to) return Rust types from `extern "C"` functions. Calling rust functions in rust code, no matter if it's `async`, is totally fine.

`into_ffi()` wraps the generated `Future` into an C-compatible one and forwards every C poll call to the original Rust `Future::poll`. Every code inside must already goes though the wrapper. You don't need multiple wrapping.
