### ISSUE TITLE
C usage example

### ISSUE THREAD

**Issue by loziniak** [oxalica/async-ffi#3]
Is this possible to use exported async functions in C code? Could you provide any example in the documentation?

**Comment by oxalica** [comment]
Do you mean async function in Rust side with async runtime in C side?
It seems hard since usually leaf async functions (socket `read`/`write`, timer sleep, etc) rely on reactor to correctly wake itself when ready, so you need to implement all of them in C side and corresponding reactor and executor. I cannot imagine the use case of C runtime exposing Rust async interface and runtime, but it should be doable.

For the inverse, Rust runtime calling async functions provided by C code. There is already an example: https://github.com/oxalica/async-ffi/blob/master/link_tests/plugin-c/plugin.c

**Comment by loziniak** [comment]
> async function in Rust side with async runtime in C side

Exactly. So, if I unerstand well, it would require implementing C version of Rust runtime, like Tokio? Perhaps in minimal version it could be easier to do? Eg. even a synchronous one, to bypass as much complexity as possible? Just thinking aloud. We could close the issue, perhaps such complex code wouldn't be a very good example.

My usecase is writing [Red language bindings to Safe Network API](https://github.com/loziniak/sn_ffi/). I also [created a Stackoverflow question](https://stackoverflow.com/questions/68302818/how-to-use-async-rust-code-in-language-without-concurrency-like-red) about it, I'll post more details there.

**Comment by oxalica** [comment]
See: https://github.com/oxalica/async-ffi/blob/master/link_tests/executor-c/main.c
